title: Tejas Iyer
description: Tejas Iyer, probabilist at the Weierstrass Institute (WIAS) Berlin.
cv_url: https://drive.google.com/file/d/1P3ZaCPplfioNJjooaLNtXXnznB_NDNia/view?usp=sharing
photo_credit: 'Photo: Petra Lein, Archives of the Mathematisches Forschungsinstitut Oberwolfach. <a href="https://creativecommons.org/licenses/by-sa/2.0/de/">CC BY-SA 2.0 DE</a>'
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - README.md
